name: Continuous testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - name: Run unit tests
        run: mvn clean test --projects '!functional-tests,!functional-tests/features,!functional-tests/mocked-tests-launcher,!functional-tests/mongodb-integration-tests-launcher'

  mocked-functional-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - name: Run mocked functional tests
        run: |
          mvn clean install -DskipTests
          mvn test --projects 'functional-tests/mocked-tests-launcher'

  mongodb-integration-functional-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - uses: supercharge/mongodb-github-action@1.3.0 #TODO Vérifier la version
        with:
          mongodb-version: 4.2
      # Il est désormais nécessaire d'installer le Shell MongoDB à la main :
      # https://github.com/actions/runner-images/issues/6626
      #      - name: Install MongoDB Shell (mongosh)
      #        run: |
      #          sudo apt-get update
      #          sudo apt-get install -y wget gnupg
      #          wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | sudo apt-key add -
      #          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
      #          sudo apt-get update
      #          sudo apt-get install -y mongodb-mongosh
      - name: Run MongoDB integration functional tests
        run: |
          mvn clean install -DskipTests
          mvn test --projects 'functional-tests/mongodb-integration-tests-launcher'
